export default [
  {
    image:
      'https://seeklogo.com/images/C/css3-logo-8724075274-seeklogo.com.png'
  },
  {
    image:
      'https://seeklogo.com/images/T/tailwind-css-logo-5AD4175897-seeklogo.com.png'
  },
  {
    image: 
      'https://seeklogo.com/images/H/html5-with-wordmark-color-logo-4259B7F24F-seeklogo.com.png'
  },
  {
    image:
      'https://seeklogo.com/images/J/javascript-logo-E967E87D74-seeklogo.com.png'
  },
  {
    image:
      'https://seeklogo.com/images/R/react-logo-7B3CE81517-seeklogo.com.png'
  },
  {
    image:
      'https://seeklogo.com/images/G/git-logo-CD8D6F1C09-seeklogo.com.png'
  },
  {
    image: 
      'https://seeklogo.com/images/G/github-logo-5F384D0265-seeklogo.com.png'
  }
];